name: Linux-weekly

on:
  push:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  Snap:
    runs-on: ubuntu-22.04
    name: Snap

    steps:
      - name: Get Processor Info
        run : lscpu | grep name

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --candidate --classic

      - name: Building & Packaging
        run: |
          sudo snapcraft --verbose --destructive-mode

      - name: Installing
        run: |
          sudo snap install --dangerous *.snap

      - name: Show info and contents
        run: |
          snap info makhber
          tree /snap/makhber/current/usr
