name: Packaging

on:
  push:
    branches:
      - '*'

jobs:
  Snap:
    runs-on: ubuntu-20.04
    name: Snap

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Building & Packaging
        id: snap_build
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: edge
          snapcraft-args: --trace

      - name: Upload Snap
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: ${{ steps.snap_build.outputs.snap }}

      - uses: snapcore/action-publish@v1
        if: ${{ github.repository_owner == 'Makhber' }}
        with:
          store_login: ${{ secrets.SNAP_STORE_LOGIN }}
          snap: ${{ steps.snap_build.outputs.snap }}
          release: beta

      - name: Installing
        run: |
          sudo snap install --dangerous *.snap

      - name: Show contents
        run: |
          tree /snap/makhber/current/usr
